### ISSUE TITLE
线上部署时出现问题

### ISSUE THREAD

**Issue by CrazyCodes** [easy-swoole/easyswoole#177]
你好，大佬。
报错信息是
```
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /var/www/RuiZhongCrawler/vendor/easyswoole/easyswoole/src/Console/Module/Auth.php:97
Stack trace:
#0 /var/www/RuiZhongCrawler/vendor/easyswoole/easyswoole/src/Console/Module/Log.php(97): EasySwoole\EasySwoole\Console\Module\Auth::currentFd()
#1 /var/www/RuiZhongCrawler/vendor/easyswoole/easyswoole/src/Logger.php(34): EasySwoole\EasySwoole\Console\Module\Log::push('[2019-03-08 10:...', 'Exception')
#2 /var/www/RuiZhongCrawler/vendor/easyswoole/trace/src/Trigger.php(50): EasySwoole\EasySwoole\Logger->log('[2019-03-08 10:...', 'Exception')
#3 /var/www/RuiZhongCrawler/vendor/easyswoole/easyswoole/src/Trigger.php(38): EasySwoole\Trace\Trigger->throwable(Object(Error))
#4 /var/www/RuiZhongCrawler/vendor/easyswoole/easyswoole/src/Core.php(284): EasySwoole\EasySwoole\Trigger->throwable(Object(Error))
#5 {main}
  thrown in /var/www/RuiZhongCrawler/vendor/easyswoole/easyswoole/src/Console/Module/Auth.php on line 97
```
出现报错信息的原因是，我在本地开发项目完成后。通过git同步到生产环境，在生产环境中 composer update 后，执行命令
```
php easyswoole start
```
获得上述错误，这时我必须使用命令
```
php vendor/bin/easyswoole install
```
重新安装(这里注意，如果我不覆盖在git版本内的配置文件是不行的)，必须要重新覆盖配置文件以及easyswoole ， 才可以达到运行的目的。

但我不能选择将配置文件忽略版本，配置文件是必须有的，不能每次在生产中重新更改

**Comment by CrazyCodes** [comment]
抱歉，我发现了解决方案。是版本问题。我本地使用的
```
"easyswoole/easyswoole": "3.x-dev",
```
生产环境是
```
"easyswoole/easyswoole": "3.x",
```
