### ISSUE TITLE
3.x-dev 异步任务失败

### ISSUE THREAD

**Issue by First-wang** [easy-swoole/easyswoole#193]
你好，我照着文档做
```php
class QuickTaskTest implements QuickTaskInterface
{
    static function run(\swoole_server $server, int $taskId, int $fromWorkerId, $flags = null)
    {
        echo "快速任务模板";

        // TODO: Implement run() method.
    }
}
```

```php
public function sendMsg()
{
        $arg = $this->caller()->getArgs();
        \EasySwoole\EasySwoole\Swoole\Task\TaskManager::async(QuickTaskTest::class);
}
```

会出现异常
```php
[2019-04-28 16:23:12][Notice][file:/application/vendor/easyswoole/easyswoole/src/Core.php][line:276]Trying to get property of non-object

Fatal error: Uncaught Error: Call to a member function finish() on integer in /application/vendor/easyswoole/easyswoole/src/Core.php:311
Stack trace:
#0 [internal function]: EasySwoole\EasySwoole\Core->EasySwoole\EasySwoole\{closure}(Object(Swoole\WebSocket\Server), 0, 0, 'App\\Task\\QuickT...')
#1 /application/vendor/easyswoole/easyswoole/src/ServerManager.php(109): Swoole\Server->start()
#2 /application/vendor/easyswoole/easyswoole/src/Core.php(136): EasySwoole\EasySwoole\ServerManager->start()
#3 /application/vendor/easyswoole/easyswoole/src/Command/DefaultCommand/Start.php(99): EasySwoole\EasySwoole\Core->start()
#4 /application/vendor/easyswoole/easyswoole/src/Command/CommandContainer.php(44): EasySwoole\EasySwoole\Command\DefaultCommand\Start->exec(Array)
#5 /application/vendor/easyswoole/easyswoole/src/Command/CommandRunner.php(52): EasySwoole\EasySwoole\Command\CommandContainer->hook('start', Array)
#6 /application/easyswoole(20): EasySwoole\EasySwoole\Command\CommandRunner->run(Array)
#7 {main}
  thrown in /application/vendor/easyswoole/easyswoole/src/Core.php on line 311
[2019-04-28 16:23:12][FatalError][file:/application/vendor/easyswoole/easyswoole/src/Core.php][line:311]Uncaught Error: Call to a member function finish() on integer in /application/vendor/easyswoole/easyswoole/src/Core.php:311
Stack trace:
#0 [internal function]: EasySwoole\EasySwoole\Core->EasySwoole\EasySwoole\{closure}(Object(Swoole\WebSocket\Server), 0, 0, 'App\\Task\\QuickT...')
#1 /application/vendor/easyswoole/easyswoole/src/ServerManager.php(109): Swoole\Server->start()
#2 /application/vendor/easyswoole/easyswoole/src/Core.php(136): EasySwoole\EasySwoole\ServerManager->start()
#3 /application/vendor/easyswoole/easyswoole/src/Command/DefaultCommand/Start.php(99): EasySwoole\EasySwoole\Core->start()
#4 /application/vendor/easyswoole/easyswoole/src/Command/CommandContainer.php(44): EasySwoole\EasySwoole\Command\DefaultCommand\Start->exec(Array)
#5 /application/vendor/easyswoole/easyswoole/src/Command/CommandRunner.php(52): EasySwoole\EasySwoole\Command\CommandContainer->hook('start', Array)
#6 /application/easyswoole(20): EasySwoole\EasySwoole\Command\CommandRunner->run(Array)
#7 {main}
  thrown
```

我在使用“投递任务模板类”创建时，也有同样的错

**Comment by kiss291323003** [comment]
你需要升级swoole
