### ISSUE TITLE
ORM  Where函数字符串条件构造引起的SQL错误

### ISSUE THREAD

**Issue by HZ-YWH** [easy-swoole/easyswoole#293]
### 					ORM  Where函数字符串条件构造引起的SQL错误

使用框架生成sql 之后 发现报错

```
string(112) "SQLSTATE[42S22] [1054] Unknown column ' (user.phone like '%官方拿货%' or user_distributor' in 'where clause'"
string(76) "/var/www/html/consumer-service/vendor/easyswoole/orm/src/Db/MysqliClient.php"
int(71)
string(1251) "#0 /var/www/html/consumer-service/vendor/easyswoole/orm/src/DbManager.php(71): EasySwoole\ORM\Db\MysqliClient->query()
#1 /var/www/html/consumer-service/vendor/easyswoole/orm/src/AbstractModel.php(1171): EasySwoole\ORM\DbManager->query()
#2 /var/www/html/consumer-service/vendor/easyswoole/orm/src/AbstractModel.php(621): EasySwoole\ORM\AbstractModel->query()
#3 /var/www/html/consumer-service/App/Models/UserDistributor.php(111): EasySwoole\ORM\AbstractModel->all()
#4 /var/www/html/consumer-service/App/Service/Distributor/AdminService.php(37): App\Models\UserDistributor->getAll()
#5 /var/www/html/consumer-service/App/HttpController/Distributor/Info.php(26): App\Service\Distributor\AdminService::getAll()
#6 /var/www/html/consumer-service/vendor/easyswoole/http/src/AbstractInterface/Controller.php(115): App\HttpController\Distributor\Info->all()
#7 /var/www/html/consumer-service/vendor/easyswoole/http/src/Dispatcher.php(182): EasySwoole\Http\AbstractInterface\Controller->__hook()
#8 /var/www/html/consumer-service/vendor/easyswoole/http/src/Dispatcher.php(137): EasySwoole\Http\Dispatcher->controllerHandler()
#9 /var/www/html/consumer-service/vendor/easyswoole/easyswoole/src/Core.php(254): EasySwoole\Http\Dispatcher->dispatch()

```

PHP代码如下 

```php
        $model = $this
            ->field($field)
            ->join('user', 'user.user_no =user_distributor.user_no', 'inner')
            ->where('user.status', self::STATUS_VALID);

        foreach ($conditions as $key => $condition) {
            if ($key === 'keyWord') {
                $model = $model
                    ->where(" (user.phone like '%$condition%' or user_distributor.title like '%$condition%') ");
            } else {
                $model = $model->where($key, $condition);
            }
        }

        $model = $model
            ->limit(parent::PER_PAGE * ($page - 1), parent::PER_PAGE)
            ->withTotalCount();


        $result['list'] = $model->all() ?? [];
```

生成 错误 SQL 如下：

```mysql
SELECT SQL_CALC_FOUND_ROWS user_distributor.*, user.phone FROM `user_distributor` INNER JOIN user on user.user_no =user_distributor.user_no WHERE  `user`.`status` = 0  AND ` (user`.`phone like '%官方拿货%' or user_distributor` AND `is_auth` = 1  LIMIT 0, 20
```

PHP代码生成正确的预期SQL 如下：

```mysql
SELECT SQL_CALC_FOUND_ROWS `user_distributor`.*, `user`.`phone` FROM `user_distributor` INNER JOIN user on user.user_no =user_distributor.user_no WHERE  `user`.`status` = 0  AND  (`user`.`phone` like '%官方拿货%' or `user_distributor`.`title` like '%官方拿货%')  AND `is_auth` = 1  LIMIT 0, 20
```

对比 两处SQL 发现错误：

字符串 .title like '%$condition%')被截断

```  mysql
` (user`
```

应该为

```mysql
（`user`
```

由此推荐为 where条件拼接错误：

在调试框架源码之后 找到查询条件构建方法

```php
   /**
     * 查询条件构建
     * @param $operator
     * @param $conditions
     */
    private function _buildCondition($operator, &$conditions)
    {
        if (empty($conditions)) {
            return;
        }
        //Prepare the where portion of the query
        $this->_query .= ' ' . $operator;
        foreach ($conditions as $cond) {
            list ($concat, $varName, $operator, $val) = $cond;
            if (strpos($varName, '.') !== false) {
                $varNameArray = explode('.', $varName);
                $varName = "`{$varNameArray[0]}`.`{$varNameArray[1]}`";
            } else {
                // 不是字符串条件，也没有包含()函数调用
                if ($val !== 'DBNULL' && strpos($varName, '(') === false) {
                    $varName = "`{$varName}`";
                }
            }

            $this->_query .= " " . $concat . " " . $varName;
            switch (strtolower($operator)) {
                case 'not in':
                case 'in':
                    $comparison = ' ' . $operator . ' (';
                    if (is_object($val)) {
                        $comparison .= $this->_buildPair("", $val);
                    } else {
                        foreach ($val as $v) {
                            $comparison .= ' ?,';
                            $this->_bindParam($v);
                        }
                    }
                    $this->_query .= rtrim($comparison, ',') . ' ) ';
                    break;
                case 'not between':
                case 'between':
                    $this->_query .= " $operator ? AND ? ";
                    $this->_bindParams($val);
                    break;
                case 'not exists':
                case 'exists':
                    $this->_query .= $operator . $this->_buildPair("", $val);
                    break;
                default:
                    if (is_array($val)) {
                        $this->_bindParams($val);
                    } elseif ($val === null) {
                        $this->_query .= ' ' . $operator . " NULL";
                    } elseif ($val != 'DBNULL' || $val == '0') {
                        $this->_query .= $this->_buildPair($operator, $val);
                    }
            }
        }
    }
```

$conditions 传入参数如下

```
array(3) {
  [0]=>
  array(4) {
    [0]=>
    string(0) ""
    [1]=>
    string(11) "user.status"
    [2]=>
    string(1) "="
    [3]=>
    int(0)
  }
  [1]=>
  array(4) {
    [0]=>
    string(3) "AND"
    [1]=>
    string(84) " (user.phone like '%官方拿货%' or user_distributor.title like '%官方拿货%') "
    [2]=>
    string(1) "="
    [3]=>
    string(6) "DBNULL"
  }
  [2]=>
  array(4) {
    [0]=>
    string(3) "AND"
    [1]=>
    string(7) "is_auth"
    [2]=>
    string(1) "="
    [3]=>
    int(1)
  }
}
```

在下面的代码中打印：

```php
if (strpos($varName, '.') !== false) {
                $varNameArray = explode('.', $varName);
                $varName = "`{$varNameArray[0]}`.`{$varNameArray[1]}`";
                var_dump($varNameArray,$varName);
            } else {
                // 不是字符串条件，也没有包含()函数调用
                if ($val !== 'DBNULL' && strpos($varName, '(') === false) {
                    $varName = "`{$varName}`";
                }
            }
```

```php
打印$varNameArray的输出
array(3) {
  [0]=>
  string(6) " (user"
  [1]=>
  string(47) "phone like '%官方拿货%' or user_distributor"
  [2]=>
  string(29) "title like '%官方拿货%') "
}
打印$varName = "`{$varNameArray[0]}`.`{$varNameArray[1]}`"的输出
string(58) "` (user`.`phone like '%官方拿货%' or user_distributor`"
```

最终就得到了 错误的SQL。

经过分析

PHP代码  ->where(" (user.phone like '%$condition%' or user_distributor.title like '%$condition%') ");

where中的值 经过  $varNameArray = explode('.', $varName); 按照点（.）来分割，生成如上长度为3  $varNameArray  

然后取$varName = "`{$varNameArray[0]}`.`{$varNameArray[1]}`";  

{$varNameArray[2]} =  "title like '%官方拿货%') " 被舍弃 最终导致错误的SQL产生。

综上所述：

类似以下的的写法 通过字符串在where中进行SQL构造的时候 不能含有 “.” ,不然就会造成如上bug 

```
->where(" (user.phone like '%$condition%' or user_distributor.title like '%$condition%') ");
```

明白了 原因之后 我将 

```
->where(" (user.phone like '%$condition%' or user_distributor.title like '%$condition%') ");
```

改造为 

```php
->where(" (phone like '%$condition%' or title like '%$condition%') ");
```

生成SQL如下：

```mysql
SELECT SQL_CALC_FOUND_ROWS `user_distributor`.*, `user`.`phone` FROM `user_distributor` INNER JOIN user on user.user_no =user_distributor.user_no WHERE  `user`.`status` = 0  AND  (`phone` like '%官方拿货%' or `title` like '%官方拿货%')  AND `is_auth` = 1  LIMIT 0, 20
```

虽然还是有问题的SQL 但是在当前情况下能用 不会报错了 

最后 希望官方早日解决上述问题

**Comment by xuanyanwow** [comment]
已在mysqli修复，字符串条件下不做任何附加处理
https://github.com/easy-swoole/mysqli/commit/7bc2c5c8c727d2cf9fbab91e7041daf295846353
