### ISSUE TITLE
配置队列服务多节点报错

### ISSUE THREAD

**Issue by wenzhizhong** [easy-swoole/easyswoole#402]
<h2 >配置队列服务多节点报错了</h2>

<h3 style="color:red!important">Fatal error: Uncaught TypeError: Argument 1 passed to EasySwoole\Queue\Consumer::__construct() must implement iole\Queue\QueueDriverInterface, null given, called in /home/wwwroot/default/easyswoole/vendor/easyswoole/queue/ line 30 and defined in /home/wwwroot/default/easyswoole/vendor/easyswoole/queue/src/Consumer.php:14</h3>

示例代码是参考文档的，如下：

<h3> App\Utility\RedisQueue1.php:</h3>

```
<?php
namespace App\Utility;

use EasySwoole\Component\Singleton;
use EasySwoole\Queue\QueueDriverInterface;
use EasySwoole\Queue\Queue;
use Swoole\Atomic\Long;
use EasySwoole\Queue\Driver\Redis;

//定义一个队列
class RedisQueue1 extends Queue
{
    use Singleton;
    public function __construct(QueueDriverInterface  $driver)
    // public function __construct(Redis $driver)
    {
        $this->driver = $driver;
        $this->atomic = new Long(0);
        $this->nodeId = '1';
    }
}
```

<h3>App\Utility\QueueProcess.php</h3>

```
<?php
namespace App\Utility;

use EasySwoole\Component\Process\AbstractProcess;
use EasySwoole\Queue\Job;

class QueueProcess extends AbstractProcess
{

    protected function run($arg)
    {
        go(function (){
            RedisQueue1::getInstance()->consumer()->listen(function (Job $job){
                echo "1===>";
                var_dump($job->getJobData());
            });
            // RedisQueue2::getInstance()->consumer()->listen(function (Job $job){
            //     echo "2===>";
            //     var_dump($job->getJobData());
            // });
        });
    }
}
```

<h3>EasySwooleEvent.php</h3>

```
<?php
namespace EasySwoole\EasySwoole;


use EasySwoole\EasySwoole\Swoole\EventRegister;
use EasySwoole\EasySwoole\AbstractInterface\Event;
use EasySwoole\Http\Request;
use EasySwoole\Http\Response;
use EasySwoole\HotReload\HotReloadOptions;
use EasySwoole\HotReload\HotReload;
use EasySwoole\EasySwoole\Config as EasySwooleConf;
use EasySwoole\ORM\Db\Config;
use EasySwoole\ORM\Db\Connection;
use EasySwoole\ORM\DbManager;

use EasySwoole\Component\Timer;
use EasySwoole\Queue\Driver\Redis;
use EasySwoole\Queue\Job;
use EasySwoole\Redis\Config\RedisConfig;
use EasySwoole\RedisPool\RedisPool;
use EasySwoole\Utility\Time;
use App\Utility\RedisQueue1;
use App\Utility\RedisQueue2;
use App\Utility\QueueProcess;

class EasySwooleEvent implements Event
{

    public static function initialize()
    {
        // TODO: Implement initialize() method.
        date_default_timezone_set('Asia/Shanghai');
        
        $config = new Config(EasySwooleConf::getInstance()->getConf('MYSQL'));
        $config->setMaxObjectNum(20);//配置连接池最大数量
        DbManager::getInstance()->addConnection(new Connection($config));
    }

    public static function mainServerCreate(EventRegister $register)
    {
        // TODO: Implement mainServerCreate() method.

        
        // 热启动
        $hotReloadOptions = new HotReloadOptions;
        $hotReload = new HotReload($hotReloadOptions);
        $hotReloadOptions->setMonitorFolder([EASYSWOOLE_ROOT . '/App']);

        $server = ServerManager::getInstance()->getSwooleServer();
        $hotReload->attachToServer($server);


        //redis pool使用请看redis 章节文档
        $config = new RedisConfig([
            'host'=>'127.0.0.1'
        ]);
        $redis = new RedisPool($config);
        $driver = new Redis($redis); 
        
        RedisQueue1::getInstance($driver);
        // RedisQueue2::getInstance($driver);

        
        //注册一个消费进程
        \EasySwoole\Component\Process\Manager::getInstance()->addProcess(new QueueProcess());
        //模拟生产者，可以在任意位置投递
        $register->add($register::onWorkerStart,function ($ser,$id){
            if($id == 0){
                Timer::getInstance()->loop(3000,function (){
                   $job = new Job();
                   $job2 = new Job();
                   $job->setJobData(['time'=>\time()]);
                   $job2->setJobData(['time'=>\time()]);
                   RedisQueue1::getInstance()->producer()->push($job);
                //    RedisQueue2::getInstance()->producer()->push($job2);
                });
            }
        });

    }

    public static function onRequest(Request $request, Response $response): bool
    {
        // TODO: Implement onRequest() method.
        return true;
    }

    public static function afterRequest(Request $request, Response $response): void
    {
        // TODO: Implement afterAction() method.
    }
}
```

<h2>报错如下：</h2>

**Fatal error: Uncaught TypeError: Argument 1 passed to EasySwoole\Queue\Consumer::__construct() must implement iole\Queue\QueueDriverInterface, null given, called in /home/wwwroot/default/easyswoole/vendor/easyswoole/queue/ line 30 and defined in /home/wwwroot/default/easyswoole/vendor/easyswoole/queue/src/Consumer.php:14**
Stack trace:
#0 /home/wwwroot/default/easyswoole/vendor/easyswoole/queue/src/Queue.php(30): EasySwoole\Queue\Consumer->__con
#1 /home/wwwroot/default/easyswoole/App/Utility/QueueProcess.php(13): EasySwoole\Queue\Queue->consumer()
#2 {main}
  thrown in /home/wwwroot/default/easyswoole/vendor/easyswoole/queue/src/Consumer.php on line 14
[2020-09-11 17:28:27][console][error]:[Uncaught TypeError: Argument 1 passed to EasySwoole\Queue\Consumer::__complement interface EasySwoole\Queue\QueueDriverInterface, null given, called in /home/wwwroot/default/easyswoolole/queue/src/Queue.php on line 30 and defined in /home/wwwroot/default/easyswoole/vendor/easyswoole/queue/src/
Stack trace:
#0 /home/wwwroot/default/easyswoole/vendor/easyswoole/queue/src/Queue.php(30): EasySwoole\Queue\Consumer->__con
#1 /home/wwwroot/default/easyswoole/App/Utility/QueueProcess.php(13): EasySwoole\Queue\Queue->consumer()
#2 {main}
  thrown at file:/home/wwwroot/default/easyswoole/vendor/easyswoole/queue/src/Consumer.php line:14]
^C
**root@qing-PC:/home/wwwroot/default/easyswoole#**

**Comment by gaobinzhan** [comment]
此报错是因为`RedisQueue1`继承`Queue`，重写了`__construct`，而`driver、atomic、nodeId`属性为私有属性，不可被子类赋值。由于你代码问题，造成`Consumer`的`__construct`失败，所以引发此错误。正确重写方式如下：
```php
public function __construct(QueueDriverInterface $driver)
{
     parent::__construct($driver);
     // 如需修改nodeId
     $this->setNodeId('xxx');
 }
```

**Comment by wenzhizhong** [comment]
明白了。没仔细看源码。谢谢！
